# Example secret values
COGNITO_DOMAIN = "https://your-cognito-domain.auth.region.amazoncognito.com"
CLIENT_ID = "your-client-id"
REDIRECT_URI = "https://your-streamlit-app-url/"

# Optional additional secrets
API_KEY = "replace-with-your-api-key"